#!/bin/bash
svn export trunk/hbrowse$1/client ../hbrowse_exports/hbrowse.test-$1-$2-$3/.
java -jar yuicompressor-2.4.6.jar -o '.js$:.js' ../hbrowse_exports/hbrowse.test-$1-$2-$3/media/scripts/*.js
java -jar yuicompressor-2.4.6.jar -o '.js$:.js' ../hbrowse_exports/hbrowse.test-$1-$2-$3/media/scripts/components/*.js
#java -jar yuicompressor-2.4.6.jar -o '.css$:.css' ../hbrowse_exports/hbrowse.test-$1-$2-$3/media/css/*.css
mkdir ../hbrowse_exports/hbrowse.test-common-$1-$2-$3
cp -R ../hbrowse_exports/hbrowse.test-$1-$2-$3/media/* ../hbrowse_exports/hbrowse.test-common-$1-$2-$3/.
cd ../hbrowse_exports/
tar -pczf hbrowse.test-$1-$2-$3.tar.gz hbrowse.test-$1-$2-$3
tar -pczf hbrowse.test-common-$1-$2-$3.tar.gz hbrowse.test-common-$1-$2-$3
